server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  quartz:
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
#        quartz:
          jobStore:
            isClustered: true

    job-store-type: jdbc
    jdbc:
      initialize-schema: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true