#server:
#  port: 8081
#

#
#  datasource:
#    url: jdbc:mysql://localhost:3306/order_db
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8090/eureka/
#  instance:
#    prefer-ip-address: true

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:8088

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer